name: indie.stunfest.fr

# Code
highlighter: pygments
exclude: ['_raws', '.gitignore', 'Gemfile*']

# Permalink format (without day)
permalink: /:title

# Pagination
paginate_path: ':num'
paginate: 500

# Markdown formatter
markdown: redcarpet
